default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: check-todo-notes-commented-code
        name: Check todo notes or commented code
        entry: python3 ./tools/check_todo_notes_commented_code/check_todo_notes_commented_code.py
        language: python
        pass_filenames: true
        require_serial: true
        args: ["-i", "./tools/check_todo_notes_commented_code/ignored_todo_notes_commented_code.txt"]

      - id: check-proprietary-files
        name: Check proprietary files
        entry: python3 ./tools/check_proprietary_files/check_proprietary_files.py
        language: python
        pass_filenames: true
        require_serial: true

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--config=.codespellrc]
