name: Issue report
description: Report incorrect or confusing descriptions, typos, grammar errors, formatting issues, etc.
labels: ['Type: Issue']
body:
  - type: dropdown
    id: document_name
    attributes:
      label: Document title
      multiple: false
      options:
        - ESP32 Technical Reference Manual
        - ESP32-S2 Technical Reference Manual
        - ESP32-S3 Technical Reference Manual
        - ESP32-C3 Technical Reference Manual
        - ESP32-C6 Technical Reference Manual
        - ESP32-H2 Technical Reference Manual
        - ESP8684 Technical Reference Manual
        - ESP32-C5 Technical Reference Manual
        - ESP32-P4 Technical Reference Manual
        - ESP32-C61 Technical Reference Manual
    validations:
      required: true
  - type: input
    id: format
    attributes:
      label: Format
      placeholder: PDF
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version number
      description: Which document version has this issue?
      placeholder: v1.0
    validations:
      required: false
  - type: input
    id: chapter
    attributes:
      label: Chapter
      description: Which chapter has this issue?
      placeholder: DMA Controller (DMA)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the issue in details.
    validations:
      required: true
